name: i_am_rich
description: I am rich
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#images/ => telling flutter to use all images in images folder. To use individual image, use images/image_name
flutter:
  uses-material-design: true
  assets:
    - images/